// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzge5f6Idt9SfKbZDRlwzzoN_5VpqQN4U',
    appId: '1:685186338765:web:3786bef502849caba6fe84',
    messagingSenderId: '685186338765',
    projectId: 'rentacar-68f1e',
    authDomain: 'rentacar-68f1e.firebaseapp.com',
    storageBucket: 'rentacar-68f1e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpB6uv3eRvsa2BwOTQaww-7FYvBkG2Lgs',
    appId: '1:685186338765:android:1425808689ab30c7a6fe84',
    messagingSenderId: '685186338765',
    projectId: 'rentacar-68f1e',
    storageBucket: 'rentacar-68f1e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBGFRmm39aUc4nYervYq5fZ8FvQ17w2j8',
    appId: '1:685186338765:ios:dce3eda0561f5a27a6fe84',
    messagingSenderId: '685186338765',
    projectId: 'rentacar-68f1e',
    storageBucket: 'rentacar-68f1e.firebasestorage.app',
    androidClientId: '685186338765-8i0s8v5pl84flldsk4g6mpnm8vine0p7.apps.googleusercontent.com',
    iosClientId: '685186338765-esn2oi10vugg7rpcbbjtuvi3euddclge.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBGFRmm39aUc4nYervYq5fZ8FvQ17w2j8',
    appId: '1:685186338765:ios:dce3eda0561f5a27a6fe84',
    messagingSenderId: '685186338765',
    projectId: 'rentacar-68f1e',
    storageBucket: 'rentacar-68f1e.firebasestorage.app',
    androidClientId: '685186338765-8i0s8v5pl84flldsk4g6mpnm8vine0p7.apps.googleusercontent.com',
    iosClientId: '685186338765-esn2oi10vugg7rpcbbjtuvi3euddclge.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzge5f6Idt9SfKbZDRlwzzoN_5VpqQN4U',
    appId: '1:685186338765:web:55e13491de1c6c9fa6fe84',
    messagingSenderId: '685186338765',
    projectId: 'rentacar-68f1e',
    authDomain: 'rentacar-68f1e.firebaseapp.com',
    storageBucket: 'rentacar-68f1e.firebasestorage.app',
  );

}